name: partition
description: A library for partitioning iterables based on predicates.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
