name: partition
description: >
  A library for partitioning iterables based on predicates.
  By default, partitioning happens lazily over the source iterable
  but eager partitioning can be used by setting the lazy parameter or
  using the partitionNow extension method.
version: 1.0.1
repository: https://github.com/AlexMeuer/dart-partition

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
